14 get posts get poststag=memesanimal=cat filter posts by date
CA-G12/Vet pull request #16
Opened 2022-10-13 14:48 UTC by mohmmed23

2022-10-13 19:05 UTC, aaamra reviewed
please add the testes

2022-10-15 07:47 UTC, aaamra requested changes

2022-10-15 07:47 UTC, aaamra commented on tsconfig.json
>        "client"
remove this line

2022-10-15 07:47 UTC, aaamra commented on src/controllers/GetPosts.ts
> +        }
you are using nested ternary operators
this makes the code unreadable

use the `if`, `else if` and `else` 

and i want from you to add [this rule](https://eslint.org/docs/rules/no-nested-ternary) to `.eslintrc.json`

and you can look at [this article](https://medium.com/@benlmsc/stop-using-nested-ternary-operators-heres-why-53e7e078e65a)  to know more about this problem

2022-10-15 07:47 UTC, aaamra commented on src/controllers/GetPosts.ts
> +  // }
to push your commented lines

2022-10-15 07:48 UTC, aaamra commented on tsconfig.json
>        "client"
i mean the client

2022-10-15 08:52 UTC, aaamra requested changes

2022-10-15 08:52 UTC, aaamra commented on src/controllers/GetPosts.ts
> +        [Op.substring]: ''
there is a bug here
if there is no `tagId` or `animalId` you put the search to empty string
that means get all the data even if there is something in the `searchContent` 

and there is no test case for this situation

2022-10-15 08:52 UTC, aaamra commented on src/controllers/GetPosts.ts
> +  const { tagId, animalId, searchCountent } = req.query
it's a common convention to use `q` in query string for searching

```suggestion
  const { tagId, animalId, q } = req.query
```

2022-10-15 09:46 UTC, aaamra approved these changes

2022-10-16 06:06 UTC, AseelL requested changes

2022-10-16 06:06 UTC, AseelL commented on src/db/build.ts
> +  const postd = await Post.findAll({})
remove the logging from here

2022-10-16 06:08 UTC, AseelL approved these changes

2022-10-16 07:35 UTC, Saeed99Madi approved these changes

2022-10-16 08:10 UTC, AseelL requested changes

2022-10-16 08:10 UTC, AseelL commented on __test__/index.test.ts
> +describe('all post ', () => {
no need to rewrite describe for each test, write a single describe for the router and give each test a descriptive name

2022-10-16 12:46 UTC, AseelL approved these changes

2022-10-17 05:52 UTC, aaamra approved these changes

2022-10-17 10:11 UTC, Saeed99Madi approved these changes

2022-10-17 10:15 UTC, salsabeelomar approved these changes

2022-10-17 10:15 UTC, merged