13 google auth and manual signin
CA-G12/Vet pull request #24
Opened 2022-10-16 12:11 UTC by Saeed99Madi

2022-10-16 15:03 UTC, mohmmed23 submitted a review, later dismissed

2022-10-17 12:37 UTC, AseelL approved these changes

2022-10-18 07:43 UTC, aaamra requested changes

2022-10-18 07:43 UTC, aaamra commented on src/config/auth.ts
> +})
delete

2022-10-18 07:43 UTC, aaamra commented on src/config/auth.ts
> +
we dont need local strategy

2022-10-18 07:43 UTC, aaamra commented on src/config/auth.ts
> +      return done(null, false, { message: 'can not found user' })
```suggestion
      return done(null, false)
```

2022-10-18 07:43 UTC, aaamra commented on src/config/auth.ts
> +      },
we need to extract the token from headers

2022-10-18 07:43 UTC, aaamra commented on src/config/environment.ts
> +
```suggestion
const googleClientId = process.env.GOOGLE_CLIENT_ID
if(!googleClientId) {
 throw new Error('invalid google client id');
}
```

2022-10-23 08:49 UTC, aaamra submitted a review, later dismissed

2022-10-23 08:52 UTC, AseelL approved these changes

2022-10-23 10:11 UTC, salsabeelomar approved these changes

2022-10-23 10:14 UTC, mohmmed23 requested changes

2022-10-23 10:14 UTC, mohmmed23 commented on __tests__/signIn.test.ts
> +      .end((err:any, res: any) => {
you should change ```any``` to interface related data type to res and err

2022-10-24 06:38 UTC, salsabeelomar submitted a review, later dismissed

2022-10-24 08:07 UTC, aaamra approved these changes

2022-10-24 08:08 UTC, AseelL approved these changes

2022-10-24 08:32 UTC, mohmmed23 approved these changes

2022-10-24 08:33 UTC, salsabeelomar approved these changes

2022-10-24 08:41 UTC, merged