create post components
CA-G12/Vet pull request #25
Opened 2022-10-16 12:36 UTC by mohmmed23

#19

2022-10-17 11:30 UTC, AseelL approved these changes

2022-10-17 13:00 UTC, AseelL approved these changes

2022-10-17 14:48 UTC, Saeed99Madi requested changes
As for Interfaces, I think You can build it in one file called `Interfaces.ts` ,instead of create file for every interface.

2022-10-17 19:11 UTC, aaamra requested changes

2022-10-17 19:11 UTC, aaamra commented on client/src/components/postCard/HoverLikes.tsx
> +}
you can import here the interfaces you created

don't repeat the interfaces

2022-10-17 19:11 UTC, aaamra commented on client/src/components/postCard/HoverLikes.tsx
> +const HoverLikes = ({ likes }:props) => (
if your props are not to many you can inline their type
```suggestion
const HoverLikes = ({ likes }:{ likes: Array<Like> }) => (
```

2022-10-17 19:11 UTC, aaamra commented on client/src/components/postCard/LikeItem.tsx
> +const LikeItem = ({ like: { id, User } } : ILike) => (
same issue here like the above one

2022-10-17 19:11 UTC, aaamra commented on client/src/components/postCard/Post.tsx
> +  };
it's a great idea to create your custom hook

i think we may use this one in other place

so you can create `hooks` folder and create a file on it for this hook

2022-10-17 19:11 UTC, aaamra commented on client/src/Interfaces/post/Ipost.tsx
> +export default IPost;
rename this file to `IPost.tsx`

2022-10-18 06:46 UTC, AseelL approved these changes

2022-10-18 06:49 UTC, Saeed99Madi approved these changes

2022-10-18 07:13 UTC, aaamra approved these changes

2022-10-18 07:35 UTC, salsabeelomar requested changes
thanks for your hard work 
you have changes in :
-  You need to separate the Comment component in the folder outside the Post component 
- You can join userInfo for comments and UserPost are the Same logic you need to Create a component for it , and put it outside the Post component

2022-10-18 12:28 UTC, AseelL approved these changes

2022-10-23 09:11 UTC, AseelL approved these changes

2022-10-23 09:36 UTC, merged