35 show all posts
CA-G12/Vet pull request #37
Opened 2022-10-20 16:57 UTC by mohmmed23

![1l](https://user-images.githubusercontent.com/92145814/197011781-a520cc4c-2b8a-43e4-8c6f-413d23689ad7.png)
![2l](https://user-images.githubusercontent.com/92145814/197011783-8266a9d2-de3c-4091-9ec0-104deedb8a0d.png)
![3](https://user-images.githubusercontent.com/92145814/197011787-2b71ef8b-2b92-4d33-858b-4f1798b90cc5.png)
![4](https://user-images.githubusercontent.com/92145814/197011792-3b478c3f-843e-4c70-8b9b-8be131a3be93.png)
![5](https://user-images.githubusercontent.com/92145814/197011804-857b7199-de33-464b-b59f-3854aa74d4d1.png)

2022-10-20 17:01 UTC, Saeed99Madi approved these changes

2022-10-23 07:01 UTC, aaamra requested changes

2022-10-23 07:01 UTC, aaamra commented on client/src/pages/Home.tsx
> +// import Avatar from '@mui/material/Avatar';
remove commented code

2022-10-23 09:06 UTC, aaamra submitted a review, later dismissed

2022-10-23 09:08 UTC, aaamra approved these changes

2022-10-23 09:17 UTC, AseelL approved these changes

2022-10-23 09:28 UTC, salsabeelomar approved these changes

2022-10-23 09:29 UTC, salsabeelomar approved these changes

2022-10-23 09:35 UTC, Saeed99Madi approved these changes

2022-10-23 09:36 UTC, merged