3 create user model
CA-G12/Vet pull request #4
Opened 2022-10-11 12:56 UTC by Saeed99Madi

2022-10-11 13:26 UTC, mohmmed23 approved these changes

2022-10-11 13:33 UTC, AseelL submitted a review, later dismissed

2022-10-12 07:04 UTC, aaamra requested changes

2022-10-12 07:04 UTC, aaamra commented on src/models/user.model.ts
> +
rename all you models and remove the `.model` from it
and use `Pascal` case

2022-10-12 07:38 UTC, AseelL submitted a review, later dismissed

2022-10-12 07:42 UTC, mohmmed23 approved these changes

2022-10-12 07:55 UTC, aaamra requested changes

2022-10-12 07:55 UTC, aaamra commented on src/models/User.ts
> +  declare role: 'ADM' | 'USR'
```suggestion
  declare role: 'ADMIN' | 'USER'
```

2022-10-12 08:09 UTC, mohmmed23 requested changes

2022-10-12 08:09 UTC, mohmmed23 commented on src/models/User.ts
> +  declare role: 'ADM' | 'USR'
add doctor role plz

2022-10-12 08:23 UTC, mohmmed23 submitted a review, later dismissed

2022-10-12 08:23 UTC, AseelL submitted a review, later dismissed

2022-10-12 08:39 UTC, mohmmed23 approved these changes

2022-10-12 08:41 UTC, AseelL approved these changes

2022-10-12 08:42 UTC, mohmmed23 approved these changes

2022-10-12 08:43 UTC, aaamra approved these changes

2022-10-12 08:43 UTC, merged