create booking && tag models
CA-G12/Vet pull request #5
Opened 2022-10-11 13:10 UTC by mohmmed23

#3

2022-10-11 13:18 UTC, salsabeelomar requested changes
change the convention for camelCase

2022-10-11 13:32 UTC, AseelL approved these changes

2022-10-12 06:32 UTC, aaamra requested changes

2022-10-12 06:32 UTC, aaamra commented on src/models/booking.model.ts
> +class booking extends Model {
when you name a class it better to use `Pascal` case
ex: `Booking`

2022-10-12 06:32 UTC, aaamra commented on src/models/tag.model.ts
> +class tag extends Model {
Same issue here
use `Pascal` case

2022-10-12 07:42 UTC, Saeed99Madi approved these changes

2022-10-12 07:56 UTC, aaamra submitted a review, later dismissed

2022-10-12 07:57 UTC, AseelL submitted a review, later dismissed

2022-10-12 08:17 UTC, aaamra approved these changes

2022-10-12 08:18 UTC, Saeed99Madi approved these changes

2022-10-12 08:24 UTC, AseelL approved these changes

2022-10-12 08:25 UTC, merged