3 create post model
CA-G12/Vet pull request #6
Opened 2022-10-11 13:21 UTC by AseelL

2022-10-11 13:27 UTC, mohmmed23 submitted a review, later dismissed

2022-10-12 06:34 UTC, aaamra requested changes

2022-10-12 06:34 UTC, aaamra commented on src/models/post.model.ts
> +class post extends Model {
when you name a class use `Pascal` case
ex: `Post`

2022-10-12 07:41 UTC, Saeed99Madi submitted a review, later dismissed

2022-10-12 07:56 UTC, mohmmed23 submitted a review, later dismissed

2022-10-12 07:59 UTC, mohmmed23 approved these changes

2022-10-12 08:01 UTC, aaamra approved these changes

2022-10-12 08:09 UTC, aaamra approved these changes

2022-10-12 08:09 UTC, mohmmed23 approved these changes

2022-10-12 08:13 UTC, merged