89 edit post
CA-G12/Vet pull request #91
Opened 2022-11-06 16:52 UTC by dev-mohmmed-alshorafa

2022-11-06 17:10 UTC, AseelL commented on src/schemes/post.ts
> +  Animal: { id: Joi.number().required(), name: Joi.string().required() },
post controllers were designed to take an id only according to the issues instructing how to build them. this is somewhat considered a redesign to that logic that should've been documented by an issue or a comment on this pr at least

2022-11-07 06:27 UTC, AseelL requested changes

2022-11-07 06:27 UTC, AseelL commented on src/controllers/PostsController.ts
> +      const { content, image, Animal, Tag, User } = req.body;
please revert the backend files to their original state, this is not how we deal with roadblocks in frontend

2022-11-07 07:07 UTC, AseelL approved these changes

2022-11-07 07:20 UTC, Saeed99Madi commented on client/src/components/PostCard/EditImagePost.tsx
> +        }}
adding the style by `sx` attribute is a bad practice

2022-11-07 07:21 UTC, Saeed99Madi commented on client/src/components/PostCard/index.tsx
> +        <section style={{ width: '100%' }} className="post-content-continuer">
also here

2022-11-07 07:23 UTC, Saeed99Madi approved these changes

2022-11-07 07:24 UTC, aaamra approved these changes

2022-11-07 07:24 UTC, merged